language: rust
rust:
  - nightly
sudo: false
script:
  - git checkout 51f31946efa148fd15be3eaa092cfb02052bc495
  - cargo build --verbose
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cargo build --verbose --manifest-path=regex-debug/Cargo.toml;
      RUSTFLAGS="-C target-feature=+ssse3" cargo test --verbose --features 'simd-accel pattern';
    else
      travis_wait cargo test --verbose;
    fi
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
notifications:
  email:
    on_success: never
